skillMetadata:
  sections:
    - name: Options
      fields:
        - name: brightness
          type: number
          label: "LED default brightness"
          value: "15"
        - name: pattern
          type: "select"
          label: "Pattern"
          options: "Amazon Echo|echo;Google Home|google"
          value: "echo"
