skillMetadata:
  sections:
    - name: "Light Options"
      fields:
        - name: brightness
          type: number
          label: "LED default brightness"
          value: "15"
        - name: pattern
          type: "select"
          label: "Pattern"
          options: "Amazon Echo|echo;Google Home|google"
          value: "echo"
    - name: "Button Options"
      fields:
        - name: long_press
          type: number
          label: "Long press delay (seconds)"
          vale: "5"
